[2022-08-05 05:56:35,120] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: my_python_dag.python_task_second manual__2022-08-05T05:56:32.968843+00:00 [queued]>
[2022-08-05 05:56:35,129] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: my_python_dag.python_task_second manual__2022-08-05T05:56:32.968843+00:00 [queued]>
[2022-08-05 05:56:35,129] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-05 05:56:35,130] {taskinstance.py:1377} INFO - Starting attempt 1 of 3
[2022-08-05 05:56:35,130] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-05 05:56:35,143] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): python_task_second> on 2022-08-05 05:56:32.968843+00:00
[2022-08-05 05:56:35,147] {standard_task_runner.py:52} INFO - Started process 1273 to run task
[2022-08-05 05:56:35,149] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_python_dag', 'python_task_second', 'manual__2022-08-05T05:56:32.968843+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/python_dag .py', '--cfg-path', '/tmp/tmpcbnw3u7c', '--error-file', '/tmp/tmp4c0dgwwp']
[2022-08-05 05:56:35,150] {standard_task_runner.py:80} INFO - Job 47: Subtask python_task_second
[2022-08-05 05:56:35,205] {task_command.py:371} INFO - Running <TaskInstance: my_python_dag.python_task_second manual__2022-08-05T05:56:32.968843+00:00 [running]> on host 31de0ba96b93
[2022-08-05 05:56:35,266] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_python_dag
AIRFLOW_CTX_TASK_ID=python_task_second
AIRFLOW_CTX_EXECUTION_DATE=2022-08-05T05:56:32.968843+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-05T05:56:32.968843+00:00
[2022-08-05 05:56:35,267] {logging_mixin.py:115} INFO - My name is Owais Own and i am 32 years old
[2022-08-05 05:56:35,267] {python.py:173} INFO - Done. Returned value was: None
[2022-08-05 05:56:35,278] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=my_python_dag, task_id=python_task_second, execution_date=20220805T055632, start_date=20220805T055635, end_date=20220805T055635
[2022-08-05 05:56:35,402] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-05 05:56:35,427] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
